$ANSIBLE_VAULT;1.1;AES256
39313336363466393862396266386266306335633765356437626166343434373162653965333165
6666373635623164323939343063326265376139326364340a323432656461343136646165626535
39616235313934386336323536376330333334313566643731616136316130353966653865386635
3839643837316132320a633463653664346361353262383532343232623964323631653431353634
39636439656163303764363639643636383164663638333230383764353634393334366661323339
3736616432663732316337323163663133363335626262626534
