- name: installing MySql Server
  ansible.builtin.package:
    name: mysql-server
    state: present
- name: enable and start service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
- name: set up password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}