  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app
  # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete {{ server_name }} file
    ansible.builtin.file:
      path: /tmp/{{ server_name }}.zip
      state: absent

  - name: download {{ server_name }} application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ server_name }}-v3.zip
      dest: /tmp/{{ server_name }}.zip

  - name: extract {{ server_name }} application
    ansible.builtin.unarchive:
      src: /tmp/{{ server_name }}.zip
      dest: /app
      remote_src: yes