- name: copy {{ server_name }} service
  ansible.builtin.template:
    src: "{{ server_name }}.service.j2"
    dest: "/etc/systemd/system/{{ server_name }}.service"
  notify: daemon-reload 

- name: start the service
  ansible.builtin.service:
    name: "{{ server_name }}"
    state: restarted
    enabled: yes     